<a href="https://colab.research.google.com/github/IvannikovG/torch_refreshing/blob/main/00pytorch_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [107]:
print('hello torcy')

hello torcy


In [106]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.1.0+cu121


In [ ]:
scalar = torch.tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar2 = torch.tensor([[[1, 23, 1], [123, 2, 1]]])

In [ ]:
scalar2.ndim

3

In [ ]:
scalar2.shape

torch.Size([1, 2, 3])

In [ ]:
rander = torch.rand(1, 2, 1, 1)

In [ ]:
print(rander.ndim)

4


In [ ]:
ones = torch.ones(size=(3, 3
                        ))

In [ ]:
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_zeros = torch.zeros_like(input=ones)

In [ ]:
ten_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
float_tensor = torch.tensor([[3, 1, 1]], dtype=torch.float16)

In [ ]:
float_tensor

tensor([[3., 1., 1.]], dtype=torch.float16)

In [ ]:
tensor = torch.tensor([1, 2, 3])

In [ ]:
print(tensor)

tensor([1, 2, 3])


In [ ]:
print(f'Device: {float_tensor.device}')
print(f'Shape: {float_tensor.shape}')
print(f'Datatype: {float_tensor.dtype}')

Device: cpu
Shape: torch.Size([1, 3])
Datatype: torch.float16


In [ ]:
print(tensor * tensor)

tensor([1, 4, 9])


In [ ]:
print(tensor.transpose())

TypeError: transpose() received an invalid combination of arguments - got (), but expected one of:
 * (int dim0, int dim1)
 * (name dim0, name dim1)


In [ ]:
print(torch.matmul(tensor, tensor))

tensor(14)


In [ ]:
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

In [ ]:
value

tensor(14)

In [ ]:
tensor = torch.tensor([[1, 2, 3], [2, 3, 1], [3, 2 ,1]])

In [ ]:
%time

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 3.58 µs


In [ ]:
tensor.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
x = torch.arange(1, 100, 10)

In [14]:
torch.mean(x.type(dtype=torch.float32))

tensor(46.)

In [15]:
x.argmax()

tensor(9)

In [22]:
y = torch.arange(1., 13.)
y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [25]:
y_reshaped = y.reshape(6, 2)
y_reshaped.shape, y_reshaped

(torch.Size([6, 2]),
 tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]))

In [30]:
y_reshaped.view(2, 6)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])

In [31]:
# View is a reshape, however shares the same memory as the original input (materialized view)

In [32]:
z = y_reshaped.view(3, 4)

In [34]:
z[:, 0] = 5

In [37]:
# Can be used to update values very sly
z, y_reshaped

(tensor([[ 5.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 5., 10., 11., 12.]]),
 tensor([[ 5.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 5., 10.],
         [11., 12.]]))

In [38]:
# Stack tensors on top of each other

In [40]:
z2 = torch.vstack([z, z])

In [41]:
z2

tensor([[ 5.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 5., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 5., 10., 11., 12.]])

In [44]:
z3 = torch.stack([z, z, z], dim= 0)
z3

tensor([[[ 5.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 5., 10., 11., 12.]],

        [[ 5.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 5., 10., 11., 12.]],

        [[ 5.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 5., 10., 11., 12.]]])

In [45]:
squizzy = torch.zeros(2, 1, 2)

In [51]:
squizzy.squeeze().unsqueeze(dim=1)

tensor([[[0., 0.]],

        [[0., 0.]]])

In [57]:
squizzy.permute(2, 0, 1)

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]]])

In [58]:
big = torch.rand((256, 256, 3))

In [63]:
big[0, 0, 0] = 9999999999999999

In [70]:
big_permuted = big.permute(0, 1, 2)

In [71]:
big[0, 0, 0] = 0

In [75]:
big_permuted[0, 0, 1:2]

tensor([0.3981])

In [78]:
import numpy as np

In [79]:
range = np.arange(1, 10)

In [81]:
t_range = torch.from_numpy(range)

In [82]:
t_range

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
range, t_range

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [84]:
t_range.dtype

torch.int64

In [85]:
range.dtype

dtype('int64')

In [86]:
tensor = torch.ones(7)

In [89]:
numpy_t = tensor.numpy()

In [90]:
tensor, numpy_t

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [104]:
RANDOM_SEED = 55
# manual seed works till the next random place
torch.manual_seed(RANDOM_SEED)
tens_1 = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
tens_2 = torch.rand(3, 4)

In [102]:
tens_1 == tens_2

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [2]:
  !nvidia-smi

Tue Mar  5 14:14:21 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [4]:
import torch

In [6]:
torch.cuda.is_available()

True

In [7]:
torch.cuda.device_count()

1

In [8]:
## Exercises

In [26]:
tensor = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)
multiplied = torch.matmul(tensor, tensor2.T)
CPU_SEED = 0
torch.manual_seed(CPU_SEED)
GPU_SEED = 1234
torch.cuda.manual_seed(GPU_SEED)
torch.manual_seed(GPU_SEED)
g_tensor_1 = torch.rand((2, 3), device='cuda')
torch.cuda.manual_seed(GPU_SEED)
torch.manual_seed(GPU_SEED)
g_tensor_2 = torch.rand((2, 3), device='cuda')

res1 = torch.matmul(g_tensor_1, g_tensor_1.T)

torch.manual_seed(7)
rand_tens = torch.rand((1, 1, 1, 10))
squeezed_rand_tens = rand_tens.squeeze()
squeezed_rand_tens.shape, rand_tens.shape

(torch.Size([10]), torch.Size([1, 1, 1, 10]))

In [27]:
g_tensor_2.device

device(type='cuda', index=0)